name: 'Chromatic Deployment'

on:
  pull_request_target:
    branches: [develop]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  chromatic:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      # 1) PR 코드 checkout (핵심)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      # 2) install
      - run: yarn

      # 3) Chromatic 실행
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build-storybook
